site_name: Cloud Architecture Docs
theme:
    name: material
  
    palette:
    - media: '(prefers-color-scheme: light)'
      primary: teal
      scheme: default
      toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      primary: teal
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


    custom_dir: docs/overrides
    
    font:
        text: 'Work Sans'
    icon:
        edit: material/pencil 
        view: material/eye
    logo: assets/CAD.png  # Path to your logo
    favicon: assets/CAD.ico  # Path to your favicon
    features:
    # - navigation.tabs
     - content.action.edit

site_url: 'http://localhost/'
repo_url: https://github.com/DanCollinsCloud/docdemo

edit_uri: edit/main/docs/

extra:
  version:
    provider: mike

plugins:
  - git-revision-date-localized
  - git-committers:
      repository: DanCollinsCloud/docdemo
      branch: main
