site_name: Cloud Architecture Docs
theme:
    name: material
    custom_dir: docs/overrides
    palette:
        primary: 'white'
        accent: 'black'
    font:
        text: 'Segoe UI'
        code: 'Roboto Mono'
    icon:
        edit: material/pencil 
        view: material/eye
    logo: logo/CAD.png  # Path to your logo
    features:
    # - navigation.tabs
     - content.action.edit

site_url: 'http://localhost/'
repo_url: https://github.com/DanCollinsCloud/docdemo

edit_uri: edit/main/docs/



extra:
  version:
    provider: mike

plugins:
  - git-revision-date-localized
  - git-committers:
      repository: DanCollinsCloud/docdemo
      branch: main
