name: Build GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: git fetch --prune --unshallow --tags

      - run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "poetry"

      - run: poetry install

      - run: poetry self add poetry-version-plugin

      - run: poetry build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-docs:
    name: Publish documentation 📚 to GitHub Pages
    needs:
      - github-release
    runs-on: ubuntu-latest

    permissions:
      contents: write # IMPORTANT: mandatory for deploying to GitHub Pages

    steps:
      - uses: actions/checkout@v4

      - run: git fetch --prune --unshallow --tags

      - run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "poetry"

      - run: poetry install --only doc

      - name: Configure git for gh-pages
        run: |
          git config --global user.name "SMP Docs Bot"
          git config --global user.email "docs@dummy.bot.com"

      - name: Set release version
        run: echo "GIT_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build and deploy documentation
        run: poetry run mike deploy --push --update-aliases ${GIT_TAG} latest